"""init schema

Revision ID: 07917ca5f670
Revises: 
Create Date: 2026-02-19 14:08:10.299427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07917ca5f670'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_manager_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_manager_id_fkey'), 'events', 'event_managers', ['manager_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
